### PR TITLE
WIP: Babel 7 upgrade

### PR DESCRIPTION
**Pull request by bjornharrtell**
Tests are failing due to presumed API breakage.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
This one seem quite relevant https://github.com/babel/babel/pull/5376.

**Comment by ef4** [comment]
Well, the silver lining is that Babel renamed all their packages. So it's easier than it would otherwise be to depend on both simultaneously.

**Comment by kernel-io** [comment]
is there any progress on this? or any details on what needs doing?

**Comment by ef4** [comment]
Closing in favor of #153.

**Pull request closed without merging**
