### PR TITLE
windows symlinks->junctions

### PR DESCRIPTION
**Pull request by ef4**
This may be a fix for #462.

### CODE REVIEW

**Comment by charlesfries** [comment]
@timmorey any tips on installing `ember-auto-import` at this commit? I am also experiencing this symlink issue on Windows and I can't figure out how to install EAI from URL since it's a monorepo.

**Comment by timmorey** [comment]
@charlesfries unfortunately, I haven't had success doing that either.  I even attempted to make a branch in my fork that had all of the built assets and the structure that was expected for the package, but then I started running into build errors in https://github.com/ef4/ember-auto-import/blob/main/packages/ember-auto-import/ts/leader.ts since I was referencing a github branch in my package.json instead of a semver range.

When I validated these changes in my build, I did so by manually editing files in my `node_modules` directory to update the affected code - not a viable production workflow.

**Comment by timmorey** [comment]
@ef4 I looked into the reported test failure, and it appears unrelated to the changes.  It looks like there was a timeout when installing dependencies: https://github.com/ef4/ember-auto-import/runs/3956772037?check_suite_focus=true#step:5:32. Re-running the test may be sufficient.

**Comment by ef4** [comment]
Thanks, this is released in 2.2.4.

**Pull request merged**
