### PR TITLE
Add v1 addons that could be consumed by v2 addons in module-scope to …

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
…a list that loads them earlier in AMD

Partially resolves: https://github.com/ef4/ember-auto-import/issues/504

### CODE REVIEW

**Comment by ef4** [comment]
Next step here is to remove things from the early boot set when their corresponding real package isn't in the app's package.json dependencies / devDependencies. This comes up in the test suite because our oldest supported ember doesn't support `@glimmer/tracking`.

**Comment by NullVoxPopuli** [comment]
The fun deepens.
on that ember-source 3.4 + fastboot scenario, we get (after removing `@glimmer/tracking` from the early boot set because it is not present in the package.json):
```
loader.js:247 Uncaught Error: Could not find module `@ember/service/index` imported from `__v1-addons__early-boot-set__`
```

**Comment by NullVoxPopuli** [comment]
I disabled the feature entirely for old ember.

**Comment by NullVoxPopuli** [comment]
Green, sans ie11 timeout

**Pull request merged**
