### PR TITLE
avoid unnecssary full page reloads

### PR DESCRIPTION
**Pull request by ef4**
Possible fix for #469

### CODE REVIEW

**Comment by gilest** [comment]
Looks good. Tried to test with the repro in #469 but ran into roadblocks installing `ember-auto-import` from git branch (monorepo package manager issues) or local directory (breaks version check).

Let me know if there's a way I can test or verify.

**Comment by SergeAstapov** [comment]
> Looks good. Tried to test with the repro in #469 but ran into roadblocks installing `ember-auto-import` from git branch (monorepo issue) or local directory (breaks version check).

just an idea, you may try to run `npm pack` in ember-auto-import branch with fix to get tgz file and use `file:` scheme in package.json (followed by yarn i/npm i/pnpm i) to point to that file from the app to test the changes.
Otherwise there is no easy way to point to package from monorepo (git submodules may be other option but that’s way to wild 😝 imo)

**Comment by gilest** [comment]
> you may try to run `npm pack` in ember-auto-import branch with the fix to get tgz file and use `file:` scheme in package.json (followed by yarn i/npm i/pnpm i) to point to that file from the app to test the changes

Ah – thanks! I hadn't tried this... but it still fails the version check.

> ember-auto-import was unable to find any copy of itself that satisfies the app's requested range of file:/Users/giles/code/ember-auto-import-2.4.0.tgz

Anyway I patched past the version check by editing the `leader.js` in `node_modules` and hardcoding the `appCandidate` version.

Fix works as expected 🙌🏻

**Comment by ef4** [comment]
This is released now anyway. Thanks.

**Pull request merged**
