### PR TITLE
fix: change from security audit

### PR DESCRIPTION
**Pull request by knownasilya**
https://www.npmjs.com/advisories/755

### CODE REVIEW

**Comment by knownasilya** [comment]
Not sure where the types are coming from..

**Comment by ef4** [comment]
`./packages/sample-typescript2` is a sample TypeScript ember app that we use in tests. It depends on `@types/ember`, which depends on `@types/handlebars`.

The new `handlebars` package contains its own types, which makes it a breaking change for any app that was already using `@types/handlebars`.

https://github.com/wycats/handlebars.js/issues/1499

**Comment by ef4** [comment]
I don't think your change really generated the error, CI broke as soon as they published handlebars 4.1.0, which is allowed by our `^` range and contains the new conflicting types.

The security fix is available in 4.0.13, so I think switching to `~` fixes the security issue while avoiding the new types.

**Comment by ef4** [comment]
Published in 1.2.20.

**Comment by nknapp** [comment]
Sorry, for the mess. I'm responsible for publishing that version. I hadn't anticipated the trouble.

Now, there is one thing I'm concerned about. Once we are through the process of removing Handlebars from DefinitelyType, 4.1 should be safe again, right? Does that mean that 4.0.13 will be broken for you then?

**Pull request merged**
