### PR TITLE
[chore] bump webpack to v5

### PR DESCRIPTION
**Pull request by gabrielcsapo**
*Motivation*

fixes https://github.com/ef4/ember-auto-import/issues/321

webpack@5 started to parse window.require, so using _non_webpack_require will tell webpack to ignore this during the build step and execute native require when executed.

### CODE REVIEW

**Comment by patocallaghan** [comment]
Nice @gabrielcsapo 🙌 It looks like CI is failing though 🤔

**Comment by ef4** [comment]
Looks like fastboot is broken due to some changes in webpack's publicPath handling.

**Comment by gabrielcsapo** [comment]
Looking into fixing CI and fastboot now.

**Comment by gabrielcsapo** [comment]
I found a fix for the publicPath issue and am chasing down the remaining errors now

**Comment by gabrielcsapo** [comment]
Updated with the latest and double checking if this fixed the failing tests.

**Comment by gabrielcsapo** [comment]
@ef4 @thoov it passes!

**Comment by ef4** [comment]
Nice work, thanks.

**Comment by gabrielcsapo** [comment]
Any update on merging this @ef4 ?

**Comment by ef4** [comment]
I was considering updating `@embroider/webpack` simultaneously, so there's one less difference between classic builds with ember-auto-import and embroider builds. But I can't actually think of a hard reason to wait for that, so this can merge and release.

This will be a semver major. But given the only-one-can-win nature of emer-auto-import, there's no way to release it without risking breakage. If an addon and the app ask for different major versions, we can't satisfy both, and instead we always let the newer one take charge. 

The breaking changes between webpack 4 and 5 don't seem very big, at least in terms of the API that typical ember apps configure. So hopefully this goes smoothly.

**Comment by yads** [comment]
@ef4 friendly nudge on getting this merged in. Is there something we can do to help?

**Comment by ef4** [comment]
Yes, I would prefer to not break apps that have custom webpack config just because one of their addons upgrades ember-auto-import. I think we should improve the leader election code to help.

 - in apps that don't directly depend on ember-auto-import, things can work as they do now.
 - in apps that don't pass any custom webpack config to ember-auto-import (or that only pass things we know are still OK in webpack 5), things can also continue to work as they do now
 - otherwise, we should restrict the leader election so that only copies of ember-auto-import that are semver-compatible with the app's copy can win
 - this may result in an addon getting an older major release of ember-auto-import than it requires, which should result in a build error.

This implies that addons will have a minimum-supported ember-auto-import major version, and if they want to increase it they should do their own semver major releases in order to not break apps.

**Comment by ef4** [comment]
Getting ready to merge this because we now have [a 2.0 rollout plan](https://github.com/ef4/ember-auto-import/pull/379).

The remaining test failures seem to be that we're loading test-only dependencies into fastboot.

**Comment by gabrielcsapo** [comment]
@ef4 looking to fix these issues now.

**Comment by gabrielcsapo** [comment]
@ef4 failures seem to be caused from moving around the sample app tests and not using the right version of fast boot.

**Comment by gabrielcsapo** [comment]
@ef4 after the tests were refactored something has changed so that now these are never passing as a result with the webpack@5 changes...

**Comment by ef4** [comment]
Thanks again @gabrielcsapo. There was one real bug caused by a change in webpack's stats format, but I was able to find it.

**Comment by gabrielcsapo** [comment]
You sir are a hero 🙌

**Pull request merged**
